---
hero_image: images/countdown-timer.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Countdown timer
description: Display a countdown timer on a Sense HAT for the Raspberry Pi
original_url: https://codeclubprojects.org/en-GB/sense-hat/countdown-timer
interests: ''
technologies: sense-hat
site_areas: codeclub, webdev
hardware: sense-hat
software: ''
version: 3
last_tested: 2017年1月1日
steps:
  - 
    title: 介绍
  - 
    title: 你将需要什么
  - 
    title: Text countdown
  - 
    title: 'Challenge: another colour'
  - 
    title: Creating a dot timer
  - 
    title: 'Challenge: timer games'
