---
hero_image: images/countdown-timer.png
theme: punainen
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Countdown timer
description: Display a countdown timer on a Sense HAT for the Raspberry Pi
original_url: https://codeclubprojects.org/en-GB/sense-hat/countdown-timer
interests: ''
technologies: sense-hat
site_areas: projektit
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Johdanto
  - 
    title: Mitä tarvitset
  - 
    title: Text countdown
  - 
    title: 'Challenge: another colour'
  - 
    title: Creating a dot timer
  - 
    title: 'Challenge: timer games'
