---
hero_image: images / countdown-timer.png
theme: vermell
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Countdown timer
description: Display a countdown timer on a Sense HAT for the Raspberry Pi
original_url: https://codeclubprojects.org/en-GB/sense-hat/countdown-timer
interests: ''
technologies: sense-hat
site_areas: projectes
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Text countdown
  - 
    title: 'Challenge: another colour'
  - 
    title: Creating a dot timer
  - 
    title: 'Challenge: timer games'
